class Exception(Traceable) {
    def init() {
        this.super(Traceable, 'init', arguments)
    }
}